### ISSUE TITLE
403 trying to create new provider

### ISSUE THREAD

**Issue by btisdall** [tobami/overmind#4]
Hi tobami and many thanks for this interesting tool.

Trying to create a new ec2 provider results in overmind just sitting there, console is printing:

Django version 1.2.5, using settings 'overmind.settings'
Development server is running at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
[09/Feb/2011 18:53:25] "GET /provider/ HTTP/1.1" 200 3917
[09/Feb/2011 18:53:25] "GET /media/css/default.css HTTP/1.1" 304 0
[09/Feb/2011 18:53:25] "GET /media/js/jquery.tooltip.min.js HTTP/1.1" 304 0
[09/Feb/2011 18:53:25] "GET /media/css/jquery.tooltip.css HTTP/1.1" 304 0
[09/Feb/2011 18:53:25] "GET /media/js/jquery.dimensions.js HTTP/1.1" 304 0
[09/Feb/2011 18:53:25] "GET /media/js/main.js HTTP/1.1" 304 0
[09/Feb/2011 18:53:25] "GET /media/images/ajax-loader.gif HTTP/1.1" 304 0
[09/Feb/2011 18:53:26] "GET /provider/new/?provider_type=EC2_EU_WEST HTTP/1.1" 200 511
[09/Feb/2011 18:54:02] "POST /provider/new/ HTTP/1.1" 403 2332

This is commit a7ce2c3372ca2b6ea8f1bda5223b59b0fc54020e, libcloud commit bd2f9ba96a78cb377cf7

libcloud seems to basically work - I have simple scripts pulling node data out already.

I'm a total django noob so bit unsure how best to start poking around for clues...

**Comment by btisdall** [comment]
Hmmm ok, it's something to do with the new CSRF stuff in django 1.2.

**Comment by tobami** [comment]
Hi, are you sure it is the CSRF stuff?. I had the issue when I tried django 1.2, but made the needed fixes. Is it working for you now? If not, are you using the UI or posting through a client? in both cases you will need admin or "Operator" status, otherwise you _will_ get a 403.

One thing you also need to take into account is that you are using master, which is a bit more complicated to configure, due to the fact that we are starting to use a job queue. So you need celery and rabbitmq. If you are having problems it may be better to use version 0.1, which should be easier to install and works fairly well. That said, if you are confortable with the celery install instrucations then go ahead.

**Comment by crook** [comment]
I have tried 0.1 version and latest version, both still have this problem
  [17/Jun/2011 05:17:31] "POST /provider/new/ HTTP/1.1" 403 2332

seem like the code didn't go into function newprovider with POST request

In file "provisioning/views.py"
 97 @permission_required('provisioning.add_provider')
 98 def newprovider(request):
 99     error = None
100     if request.method == 'POST':
101         error, form, prov = save_new_provider(request.POST)
102         if error is None:
103             return HttpResponse('<p>success</p>')
104     else:
105         form = ProviderForm(request.GET.get("provider_type"))
106     if error == 'form':
107         error = None
108     return render_to_response('provider_form.html',
109         { 'form': form, 'error': error })

**Comment by tobami** [comment]
Let's check the conditions again: A couple of questions:
- You are trying to create a new EC2 Provider using the UI, right?
- You say you have scripts which successfully pull the data. I assume that means you where able to create a non-EC2 Provider?

So you are getting a `403 Forbidden`, which means that you cannot login because your user has no "provisioning.add_provider" permissions. What user are you using?

That would of course be a bug, because in the UI, either you are logged in with a user that has the rights, or you don't, in which case you shouldn't even be given the possibility of clicking to create a provider.

**Comment by crook** [comment]
1. yes, I use UI to create a new EC2 provider
2. i guess 'btisdall' means that he can use libcloud API to control EC2. I also tried libclould API manually
   and the libcolud works well. so it should be the overmind's issue
3. I use the supera ccount creeated by './manage.py syncdb' command. Even that, the step by step debug show that
   the permission is ok, snice funtion has_perm in file django/contrib/auth/backends.py return True. 

sorry for my poor debug skill, I can't find more clues for you. 
In the last, thank you for this great tool and it interests me a lot.

**Comment by tobami** [comment]
ok. I will look again at this issue when development resumes. At the moment I am further developing LittleChef, a parallel project that should bring Configuration Management to Overmind.

Glad to hear you find Overmind useful.

**Comment by charleskaminski** [comment]
This bug is rendering overmind unusable. Even though the interface hangs, you can see the request and the error response using fiddler.  For what it's worth, I've included the http request and the error response below for debugging.

From Fiddler (asterisk indicates data I've omitted):

-------------  REQUEST ---------------------
POST http://***_:8015/provider/new/ HTTP/1.1
Host: ***_:8015
Connection: keep-alive
Content-Length: 123
Origin: http://***_:8015
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/535.1 (KHTML, like Gecko) Chrome/14.0.835.202 Safari/535.1
Content-Type: application/x-www-form-urlencoded
Accept: */_
Referer: http://***_:8015/provider/
Accept-Encoding: gzip,deflate,sdch
Accept-Language: en-US,en;q=0.8
Accept-Charset: ISO-8859-1,utf-8;q=0.7,_;q=0.3
Cookie: sessionid=b82b03f03257bd28b82207dd1d312e16; csrftoken=4b059496e31493fe842c71d47d5cbf4f

name=test&secret_key=*********_&access_key=**_***&provider_type=EC2_US_EAST

------------------- RESPONSE  -------------------------------------

HTTP/1.0 403 FORBIDDEN
Date: Fri, 21 Oct 2011 17:50:21 GMT
Server: WSGIServer/0.1 Python/2.6.6
Vary: Cookie
Content-Type: text/html
Set-Cookie: csrftoken=4b059496e31493fe842c71d47d5cbf4f; expires=Fri, 19-Oct-2012 17:50:21 GMT; Max-Age=31449600; Path=/

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="robots" content="NONE,NOARCHIVE">
  <title>403 Forbidden</title>
  <style type="text/css">
    html \* { padding:0; margin:0; }
    body \* { padding:10px 20px; }
    body \* \* { padding:0; }
    body { font:small sans-serif; background:#eee; }
    body>div { border-bottom:1px solid #ddd; }
    h1 { font-weight:normal; margin-bottom:.4em; }
    h1 span { font-size:60%; color:#666; font-weight:normal; }
    #info { background:#f6f6f6; }
    #info ul { margin: 0.5em 4em; }
    #info p, #summary p { padding-top:10px; }
    #summary { background: #ffc; }
    #explanation { background:#eee; border-bottom: 0px none; }
  </style>
</head>
<body>

<div id="summary">
  <h1>Forbidden <span>(403)</span></h1>
  <p>CSRF verification failed. Request aborted.</p>

</div>


<div id="info">
  <h2>Help</h2>
    
    <p>Reason given for failure:</p>
    <pre>
    CSRF token missing or incorrect.
    </pre>
    

  <p>In general, this can occur when there is a genuine Cross Site Request Forgery, or when
  <a
  href='http://docs.djangoproject.com/en/dev/ref/contrib/csrf/#ref-contrib-csrf'>Django's
  CSRF mechanism</a> has not been used correctly.  For POST forms, you need to
  ensure:</p>

  <ul>
    <li>The view function uses <a
    href='http://docs.djangoproject.com/en/dev/ref/templates/api/#subclassing-context-requestcontext'><code>RequestContext</code></a>
    for the template, instead of <code>Context</code>.</li>

    <li>In the template, there is a <code>{% csrf_token
    %}</code> template tag inside each POST form that
    targets an internal URL.</li>

    <li>If you are not using <code>CsrfViewMiddleware</code>, then you must use
    <code>csrf_protect</code> on any views that use the <code>csrf_token</code>
    template tag, as well as those that accept the POST data.</li>

  </ul>

  <p>You're seeing the help section of this page because you have <code>DEBUG =
  True</code> in your Django settings file. Change that to <code>False</code>,
  and only the initial error message will be displayed.  </p>

  <p>You can customize this page using the CSRF_FAILURE_VIEW setting.</p>
</div>


</body>
</html>

**Comment by tobami** [comment]
@charleskaminski. Thanks to your traceback it was 100% clear that CSRF protection was the problem. Django 1.3 added the protection to Ajax request, and that's why Overmind was breaking. Adding the CSRFToken header to all ajax requests should solve it.

@All: great that you are still interested in this application despite no updates for so many months!
Any other things that prevent you from using it? Wishes? other feedback?

**Comment by charleskaminski** [comment]
Of interest..
https://docs.djangoproject.com/en/1.3/ref/contrib/csrf/#ajax

**Comment by tobami** [comment]
yep, that is exactly what I did ;-)
Did it work for you?

**Comment by charleskaminski** [comment]
Still haven't been able to launch a node yet. Opened up bug:  https://github.com/tobami/overmind/issues/6
